### PR TITLE
TASK-444

### PR DESCRIPTION
**Pull request by imedina**
CI/CD imporovements

### CODE REVIEW

**Comment by imedina** [comment]
Task linked: [TASK-444 CI/CD improvements](https://app.clickup.com/t/36631768/TASK-444)

**Comment by halender** [comment]
Task linked: [TASK-446 Create a new workflow to run Task branches](https://app.clickup.com/t/36631768/TASK-446)

**Comment by halender** [comment]
Task linked: [TASK-444 CI/CD improvements](https://app.clickup.com/t/36631768/TASK-444)

**Comment by halender** [comment]
Task linked: [TASK-444 CI/CD improvements](https://app.clickup.com/t/36631768/TASK-444)

**Comment by halender** [comment]
Task linked: [TASK-444 CI/CD improvements](https://app.clickup.com/t/36631768/TASK-444)

**Comment by halender** [comment]
Task linked: [TASK-444 CI/CD improvements](https://app.clickup.com/t/36631768/TASK-444)

**Review by jmjuanes — APPROVED** [review]

**Pull request merged**
